### ISSUE TITLE
VyOS refers to shared image while using linked_base: false

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-registry#107]
There's a shared disk image "empty8G.qcow2" used by these appliances:
- checkpoint-gaia.gns3a
- cisco-asa.gns3a
- hp-vsr1001.gns3a
- vyos.gns3a

I see some trouble here (please correct me if I'm wrong). VyOS has the linked_base set to false, which means the base image (empty8G.qcow2) is being overwritten during the install. The description mentions to change linked_base to True after the installation, so the VM instances will use their own snapshots later on.

Now if we overwrite the base empty8G.qcow2 during the VyOS installation, how the other appliances will use the same image? I think they expect an empty disk file; or am I missing something here?

If I'm correct, VyOS should have a dedicated image, something like vyos8G.qcow2.

**Comment by noplay** [comment]
You are right it's an issue.

After reflexion I propose to rollback the linked_base flag because it's the only appliance where we use it. Other appliance with installation from ISO for the moment make a new install each time you drag the appliance. Do you agree?

We should found a way to install the OS and keep the install from GNS3. I propose: https://github.com/GNS3/gns3-server/issues/489

**Comment by adosztal** [comment]
I agree. VyOS installation takes less than a minute, it can be done every time. Advanced users might turn it off&on on the GUI but shouldn't be a default setting for everyone.
