### ISSUE TITLE
How many patch versions should we keep in a template?

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-registry#146]
This problem might first appear at Fortinet appliances. Fortinet pushes new images quite fast; it's a common thing to have 8-10+ patch versions (e.g. 5.2 is currently 5.2.8). Should it be limited to keep the import dialogue tidy, or let's squeeze in as much as we can?

**Comment by noplay** [comment]
I think we should keep all the version because a user could want to import an old version. And if it's start to be an issue we need to improve the IHM.

Also I see a side effect of having all version, we create a database of appliance images for the futur. Allowing stuff like detecting what is an image use in a topology.
