### ISSUE TITLE
Juniper vsrx

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-registry#21]
Free trial with kvm image available here:
http://www.juniper.net/us/en/dm/free-vsrx-trial/

**Comment by noplay** [comment]
I pushed a support for a old release:
d704aaa6df18aa5165dc3b8ea3064330ddde8f3e

**Comment by ehlers** [comment]
Your vSRX appliance works absolutely fine. I would lower the ram to 1024 (2000 is too much) and change the interface naming to "ge-0/0/{0}", but that's all.

Juniper also released a slightly newer vSRX:
filename: junos-vsrx-12.1X47-D20.7-domestic.ova
filesize: 235960320
md5sum: 5a992d618b8b40fa4a3cffd234636643

Maybe you can additionally include that version in the appliance.

Since some weeks, a newer version 15.1 is available. It's essentially a linux VM, that starts the vSRX FreeBSD VM and a packet forwarding instance. It needs way more resources (file size 2-3 GB instead of 230MB, RAM 3-4GB instead of 1GB). During my tests of v15.1X49-D15 I got the following experience:
- Boots and runs fine with VMware fusion, but one Core is constantly active
- Didn't got it working on Debian Wheezy, even using virt-manager and qemu 2.4 didn't help

So because of the very big resource needs, I recommend to stay away from it. As Juniper tested it with Ubuntu, it might work in the GNS3 VM, but I haven't tested.

**Comment by noplay** [comment]
I suggest we create a second appliance vSRX-KVM for version 15 and later.

**Comment by noplay** [comment]
junos-vsrx-12.1X47-D20.7-domestic.ova updated

**Comment by trueobsession** [comment]
Can anyone install vsrx-15 kvm image on GNS3 VM..?
