### ISSUE TITLE
Update FRRouting appliance to latest

### ISSUE THREAD

**Issue by pcapdevila** [GNS3/gns3-registry#420]
Hello,
I've seen that the FRR appliance is outdated as of:  https://github.com/FRRouting/frr/releases/tag/frr-7.0

In fact, I would like to test the master branch. So if there is way I can help and contribute the 7.0 image, this way I would learn how to build the master image.

Thanks!

**Comment by asenci** [comment]
Looks like they no longer provide a QCOW image for the new releases, so you would need to build one yourself, and add it to the template definition.
It would probably be easier to build a Docker image, since they provide a Dockerfile with the source: https://github.com/FRRouting/frr/blob/master/docker/alpine/Dockerfile

Another option would be to deploy a Linux appliance (QCOW or Docker) and install FRR on the appliance (packages are available for Debian/Ubuntu and RHEL/CentOS).

**Comment by adosztal** [comment]
I'll update the appliance this week.

**Comment by adosztal** [comment]
Update in #421, the images are already of SourceForge.
