### ISSUE TITLE
openvswitch 28

### ISSUE THREAD

**Issue by vasu-dasari** [GNS3/gns3-registry#426]
I am trying to build and use a latest openvswitch image built from docker/openvswitch28 directory. I could build the image from there. I just had to modify the RUN command to:
`RUN apk update && apk add openvswitch && rm -rf /var/cache/apk/*`

I load the image to a template `gns3-openvswitch28`. And then instantiated and started the container. On going to console I see this error:

```
gns3-openvswitch28-1 console is now available... Press RETURN to get started.
/etc/openvswitch/conf.db does not exist ... (warning).
Creating empty database /etc/openvswitch/conf.db.
Starting ovsdb-server.
system ID not configured, please use --system-id ... failed!
Configuring Open vSwitch system IDs.
modprobe: can't change directory to '/lib/modules': No such file or directory
Inserting openvswitch module ... failed!
rmmod: can't unload module 'bridge': Resource temporarily unavailable
removing bridge module ... failed!

```

Can someone please tell me how to resolve this?

**Comment by b-ehlers** [comment]
Well, it's quite likely a bit late for an answer. Nevertheless, the openvswitch appliance requires, that the kernel module openvswitch is loaded in the host OS before the appliance is started.

If you are using the GNS3VM, you need to load it in this VM. Otherwise, if you are running it in a local or remote linux server, you need to load it there.

Normally this procedure should work:
Either add the line `openvswitch` in /etc/modules or create a file /etc/modules-load.d/openvswitch.conf with a single line `openvswitch`. Afterwards reboot the linux system.

**Comment by vasu-dasari** [comment]
I have created my own OVS appliance and started using it in user mode. And it satisfies my requirement. Thanks for the reply. I totally forgot about this issue too. Will close this.
