### ISSUE TITLE
Checksum Errors - Juniper VMx, Mikrotik

### ISSUE THREAD

**Issue by nwwn02** [GNS3/gns3-registry#515]
Hello,

I am attempting to install the Juniper VMx Template (vfp and vcp) as well as a Mikrotik Cloud router. 

Upon selecting the template to install I receive this error:

![Screenshot_20200419_095140](https://user-images.githubusercontent.com/63962347/79689546-95fbe100-8223-11ea-833f-624cfcb53e93.png)

Is there somewhere else I should be getting the images from to import? Currently, I am getting the .gns3a from https://www.gns3.com/marketplace/appliance/juniper-vmx-vcp

**Comment by Gelob** [comment]
You are getting that error because you haven't imported any images, which is why they show missing. You need to get the images from juniper.net. If you want to run v19 you'll need to have access to the VMX download page here. This may or may not require some juniper subscription, you can always make an account and ask them for access to VMX downloads. https://support.juniper.net/support/downloads/?p=vmx

Otherwise anyone can get access to the VMX eval images below and you can run 17.4R1.16 which is in the GNS3 repository list.

**Comment by Gelob** [comment]
@grossmj can you close this out?
